# Generated by Django 6.0.1 on 2026-01-26 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_categoria_options_alter_categoria_orden_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', '🔔 Recibido'), ('COCINA', '🔥 En Cocina'), ('RUTA', '🏍️ En Ruta'), ('PROBLEMA', '⚠️ Problema / No Recibido'), ('ENTREGADO', '✅ Entregado'), ('CANCELADO', '❌ Cancelado')], default='RECIBIDO', max_length=20),
        ),
    ]
