# Generated by Django 6.0.1 on 2026-01-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_repartidor_alter_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(default='FoodBack', max_length=100)),
                ('hora_apertura', models.TimeField(default='08:00')),
                ('hora_cierre', models.TimeField(default='22:00')),
                ('lunes_abierto', models.BooleanField(default=True)),
                ('martes_abierto', models.BooleanField(default=True)),
                ('miercoles_abierto', models.BooleanField(default=True)),
                ('jueves_abierto', models.BooleanField(default=True)),
                ('viernes_abierto', models.BooleanField(default=True)),
                ('sabado_abierto', models.BooleanField(default=True)),
                ('domingo_abierto', models.BooleanField(default=True)),
                ('mensaje_cierre', models.TextField(default='Ups, la cocina descansa. 😴\nVolvemos mañana con las pilas cargadas.', help_text='Mensaje gracioso que verá el cliente cuando esté cerrado.')),
            ],
            options={
                'verbose_name': '⚙️ Configuración del Negocio',
            },
        ),
        migrations.CreateModel(
            name='DiaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('abierto', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '📅 Día Especial / Feriado',
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', '⏳ Pendiente de Pago'), ('RECIBIDO', '🔔 Recibido'), ('COCINA', '🔥 En Cocina'), ('RUTA', '🏍️ En Ruta'), ('PROBLEMA', '⚠️ Problema / No Recibido'), ('ENTREGADO', '✅ Entregado'), ('CANCELADO', '❌ Cancelado')], default='RECIBIDO', max_length=20),
        ),
    ]
