# Generated by Django 6.0.1 on 2026-01-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_configuracionnegocio_diaespecial_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaespecial',
            name='hora_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaespecial',
            name='hora_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
