# Generated by Django 6.0.1 on 2026-01-30 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_diaespecial_hora_apertura_diaespecial_hora_cierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', '⏳ Pendiente de Pago'), ('RECIBIDO', '🔔 Recibido (Confirmado)'), ('COCINA', '🔥 En Cocina'), ('RUTA', '🏍️ En Ruta'), ('ENTREGADO', '✅ Entregado'), ('PROBLEMA', '⚠️ Problema / No Recibido'), ('CANCELADO', '❌ Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='OpcionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='pedidos.producto')),
            ],
        ),
    ]
