# Generated by Django 6.0.1 on 2026-01-30 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_estado_opcionproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.opcionproducto'),
        ),
    ]
