# Generated by Django 6.0.1 on 2026-01-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_detallepedido_opcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='extras',
            field=models.ManyToManyField(blank=True, to='pedidos.extra'),
        ),
        migrations.AddField(
            model_name='producto',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='productos', to='pedidos.extra'),
        ),
    ]
