# Generated by Django 4.2.17 on 2026-02-06 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_extra_detallepedido_extras_producto_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnegocio',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2026, 3, 7), verbose_name='Vencimiento Suscripción'),
        ),
    ]
