# Generated by Django 4.2.17 on 2026-06-01 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_configuracionnegocio_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2026, 7, 1), verbose_name='Vencimiento Suscripción'),
        ),
    ]
