# Generated by Django 4.2.17 on 2026-06-03 02:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_pedido_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_pago_verificado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pago_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='wompi_id_enlace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='wompi_id_transaccion',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='wompi_referencia',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='wompi_url_enlace',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2026, 7, 2), verbose_name='Vencimiento Suscripción'),
        ),
        migrations.CreateModel(
            name='PagoWompi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PEDIDO', 'Pedido de cliente'), ('SUSCRIPCION', 'Suscripción SaaS')], max_length=20)),
                ('referencia', models.CharField(db_index=True, max_length=150, unique=True)),
                ('id_enlace', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('url_enlace', models.URLField(blank=True, max_length=700, null=True)),
                ('id_transaccion', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('CREADO', 'Enlace creado'), ('PENDIENTE', 'Pendiente de confirmación'), ('APROBADO', 'Pago aprobado'), ('RECHAZADO', 'Pago rechazado'), ('CANCELADO', 'Pago cancelado'), ('ERROR', 'Error de validación')], default='CREADO', max_length=20)),
                ('es_aprobada', models.BooleanField(default=False)),
                ('raw_creacion', models.JSONField(blank=True, default=dict)),
                ('raw_redirect', models.JSONField(blank=True, default=dict)),
                ('raw_webhook', models.JSONField(blank=True, default=dict)),
                ('ultimo_error', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('configuracion_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_suscripcion', to='pedidos.configuracionnegocio')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_wompi', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Pago Wompi',
                'verbose_name_plural': 'Pagos Wompi',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
