# Generated by Django 4.2.17 on 2026-09-07 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_pedido_fecha_pago_verificado_pedido_pago_verificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tracking_token',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2026, 10, 7), verbose_name='Vencimiento Suscripción'),
        ),
    ]
