# Generated by Django 4.2.17 on 2026-09-07 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_backfill_tracking_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tracking_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
