# Generated by Django 4.2.17 on 2026-09-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_enforce_unique_tracking_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagowompi',
            name='id_transaccion',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
