# Generated by Django 4.2.17 on 2026-09-08 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_alter_pagowompi_id_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagowompi',
            name='cliente_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='EventoPagoWompi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('categoria', models.CharField(choices=[('RECHAZO_CLIENTE', 'Rechazo bancario / cliente'), ('ERROR_TECNICO', 'Error técnico'), ('SEGURIDAD', 'Evento de seguridad'), ('INFO', 'Información')], db_index=True, max_length=30)),
                ('origen', models.CharField(choices=[('INICIO', 'Inicio de pago'), ('WEBHOOK', 'Webhook'), ('REDIRECT', 'Redirect'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('codigo', models.CharField(blank=True, max_length=80)),
                ('mensaje', models.TextField(blank=True)),
                ('cuenta_para_cliente', models.BooleanField(default=False)),
                ('cuenta_para_global', models.BooleanField(default=False)),
                ('clave_evento', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('configuracion_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_pago_wompi', to='pedidos.configuracionnegocio')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='pedidos.pagowompi')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_pago_wompi', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Evento de pago Wompi',
                'verbose_name_plural': 'Eventos de pago Wompi',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EstadoPasarelaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloqueo_manual', models.BooleanField(default=False)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('codigo_motivo', models.CharField(blank=True, max_length=80)),
                ('motivo', models.TextField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('configuracion_negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_pasarela', to='pedidos.configuracionnegocio')),
            ],
            options={
                'verbose_name': 'Estado de pasarela',
                'verbose_name_plural': 'Estados de pasarela',
            },
        ),
    ]
