# Generated by Django 4.2.17 on 2026-09-09 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pedidos.models
import uuid



class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0016_pagowompi_cliente_token_hash_eventopagowompi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Identificador único del negocio. Más adelante podrá utilizarse para subdominios.', max_length=100, unique=True)),
                ('habilitado', models.BooleanField(default=True, help_text='Control administrativo de plataforma. No representa el estado de la suscripción.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='fecha_vencimiento',
            field=models.DateField(
                default=pedidos.models.fecha_vencimiento_por_defecto,
                verbose_name='Vencimiento Suscripción',
            ),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ARCHIVADA', 'Archivada')], db_index=True, default='ACTIVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='pedidos.tenant')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['tenant', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('OWNER', 'Dueño'), ('MANAGER', 'Gerente')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='pedidos.tenant')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foodback_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
            },
        ),
        migrations.AddConstraint(
            model_name='sucursal',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_sucursal_slug_por_tenant'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['tenant', 'rol'], name='membership_tenant_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('tenant', 'usuario'), name='unique_usuario_por_tenant'),
        ),
    ]
