# Generated by Django 4.2.17 on 2026-09-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_tenant_alter_configuracionnegocio_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnegocio',
            name='sucursal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuracion', to='pedidos.sucursal'),
        ),
    ]
