# Generated by Django 4.2.17 on 2026-09-10 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_configuracionnegocio_sucursal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaespecial',
            options={'verbose_name': '📅 Día Especial / Feriado', 'verbose_name_plural': '📅 Días Especiales / Feriados'},
        ),
        migrations.AddField(
            model_name='diaespecial',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal a la que pertenece esta excepción de horario.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dias_especiales', to='pedidos.sucursal'),
        ),
        migrations.AlterField(
            model_name='diaespecial',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AddIndex(
            model_name='diaespecial',
            index=models.Index(fields=['sucursal', 'fecha'], name='diaesp_sucursal_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='diaespecial',
            constraint=models.UniqueConstraint(fields=('sucursal', 'fecha'), name='unique_dia_especial_por_sucursal'),
        ),
    ]
