# Generated by Django 4.2.17 on 2026-09-10 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0019_alter_diaespecial_options_diaespecial_sucursal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.sucursal'),
        ),
    ]
