# Generated by Django 4.2.17 on 2026-09-10 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0020_pedido_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='pedidos.tenant'),
        ),
        migrations.AddField(
            model_name='extra',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extras_catalogo', to='pedidos.tenant'),
        ),
    ]
