# Generated by Django 4.2.17 on 2026-09-10 06:47

from django.db import migrations, models
import django.db.models.deletion
import pedidos.models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0021_categoria_tenant_extra_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagowompi',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_wompi', to='pedidos.tenant'),
        ),
        migrations.CreateModel(
            name='SuscripcionTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('GRACIA', 'Período de gracia'), ('SUSPENDIDA', 'Suspendida'), ('CANCELADA', 'Cancelada')], db_index=True, default='ACTIVA', max_length=20)),
                ('fecha_vencimiento', models.DateField(default=pedidos.models.fecha_vencimiento_por_defecto)),
                ('gracia_hasta', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='suscripcion', to='pedidos.tenant')),
            ],
            options={
                'verbose_name': 'Suscripción de Tenant',
                'verbose_name_plural': 'Suscripciones de Tenant',
            },
        ),
    ]
