# Generated by Django 4.2.17 on 2026-09-10 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0022_pagowompi_tenant_suscripciontenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='pedidos.tenant'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('tenant', 'telefono'), name='unique_cliente_telefono_por_tenant'),
        ),
    ]
