# Generated by Django 4.2.17 on 2026-09-10 17:00

from django.db import migrations

def backfill_cliente_tenant(
    apps,
    schema_editor,
):
    Tenant = apps.get_model(
        "pedidos",
        "Tenant",
    )

    Cliente = apps.get_model(
        "pedidos",
        "Cliente",
    )

    Pedido = apps.get_model(
        "pedidos",
        "Pedido",
    )

    db_alias = (
        schema_editor.connection.alias
    )

    tenants = list(
        Tenant.objects
        .using(db_alias)
        .values_list(
            "id",
            flat=True,
        )
    )

    clientes = (
        Cliente.objects
        .using(db_alias)
        .filter(
            tenant__isnull=True
        )
    )

    for cliente in clientes.iterator():

        tenant_ids = list(
            Pedido.objects
            .using(db_alias)
            .filter(
                cliente_id=cliente.id,
                sucursal__isnull=False,
            )
            .values_list(
                "sucursal__tenant_id",
                flat=True,
            )
            .distinct()
        )

        if len(tenant_ids) == 1:
            tenant_id = tenant_ids[0]

        elif (
            len(tenant_ids) == 0
            and len(tenants) == 1
        ):
            tenant_id = tenants[0]

        elif len(tenant_ids) > 1:
            raise RuntimeError(
                (
                    f"Cliente {cliente.id} "
                    "está relacionado con pedidos "
                    "de más de un Tenant."
                )
            )

        else:
            raise RuntimeError(
                (
                    f"No fue posible determinar "
                    f"el Tenant del Cliente "
                    f"{cliente.id}."
                )
            )

        (
            Cliente.objects
            .using(db_alias)
            .filter(
                pk=cliente.pk
            )
            .update(
                tenant_id=tenant_id
            )
        )

    restantes = (
        Cliente.objects
        .using(db_alias)
        .filter(
            tenant__isnull=True
        )
        .count()
    )

    if restantes:
        raise RuntimeError(
            (
                "La migración terminó con "
                f"{restantes} Cliente(s) "
                "sin Tenant."
            )
        )




class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0023_cliente_tenant_alter_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.RunPython(
            backfill_cliente_tenant,
            migrations.RunPython.noop,
        ),
    ]
