# Generated by Django 4.2.17 on 2026-09-10 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0024_backfill_cliente_tenant_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='pedidos.tenant'),
        ),
    ]
