# Generated by Django 4.2.17 on 2026-09-10 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0025_alter_cliente_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopasarelapago',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estado_pasarela_wompi', to='pedidos.tenant'),
        ),
        migrations.AddField(
            model_name='eventopagowompi',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_pago_wompi', to='pedidos.tenant'),
        ),
        migrations.AlterField(
            model_name='estadopasarelapago',
            name='configuracion_negocio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado_pasarela', to='pedidos.configuracionnegocio'),
        ),
    ]
