# Generated by Django 4.2.17 on 2026-09-10 21:13

from django.db import migrations


def backfill_wompi_tenant(
    apps,
    schema_editor,
):
    EventoPagoWompi = apps.get_model(
        "pedidos",
        "EventoPagoWompi",
    )
    EstadoPasarelaPago = apps.get_model(
        "pedidos",
        "EstadoPasarelaPago",
    )

    db_alias = schema_editor.connection.alias

    # ---------------------------------
    # EstadoPasarelaPago
    # ---------------------------------

    estados = (
        EstadoPasarelaPago.objects
        .using(db_alias)
        .filter(
            tenant__isnull=True
        )
    )

    for estado in estados.iterator():

        tenant_id = (
            EstadoPasarelaPago.objects
            .using(db_alias)
            .filter(
                pk=estado.pk
            )
            .values_list(
                "configuracion_negocio__sucursal__tenant_id",
                flat=True,
            )
            .first()
        )

        if not tenant_id:
            raise RuntimeError(
                (
                    "No fue posible determinar "
                    "el Tenant de "
                    "EstadoPasarelaPago "
                    f"{estado.pk}."
                )
            )

        duplicado = (
            EstadoPasarelaPago.objects
            .using(db_alias)
            .filter(
                tenant_id=tenant_id
            )
            .exclude(
                pk=estado.pk
            )
            .exists()
        )

        if duplicado:
            raise RuntimeError(
                (
                    "Existen varios estados "
                    "de pasarela para el mismo "
                    f"Tenant {tenant_id}. "
                    "Requiere conciliación manual."
                )
            )

        (
            EstadoPasarelaPago.objects
            .using(db_alias)
            .filter(
                pk=estado.pk
            )
            .update(
                tenant_id=tenant_id
            )
        )

    # ---------------------------------
    # EventoPagoWompi
    # ---------------------------------

    eventos = (
        EventoPagoWompi.objects
        .using(db_alias)
        .filter(
            tenant__isnull=True
        )
    )

    for evento in eventos.iterator():

        datos = (
            EventoPagoWompi.objects
            .using(db_alias)
            .filter(
                pk=evento.pk
            )
            .values(
                "pago__tenant_id",
                "pedido__sucursal__tenant_id",
                "configuracion_negocio__sucursal__tenant_id",
            )
            .first()
        )

        tenant_id = (
            datos["pago__tenant_id"]
            or datos[
                "pedido__sucursal__tenant_id"
            ]
            or datos[
                "configuracion_negocio__sucursal__tenant_id"
            ]
        )

        if not tenant_id:
            raise RuntimeError(
                (
                    "No fue posible determinar "
                    "el Tenant de "
                    "EventoPagoWompi "
                    f"{evento.pk}."
                )
            )

        (
            EventoPagoWompi.objects
            .using(db_alias)
            .filter(
                pk=evento.pk
            )
            .update(
                tenant_id=tenant_id
            )
        )

    estados_restantes = (
        EstadoPasarelaPago.objects
        .using(db_alias)
        .filter(
            tenant__isnull=True
        )
        .count()
    )

    eventos_restantes = (
        EventoPagoWompi.objects
        .using(db_alias)
        .filter(
            tenant__isnull=True
        )
        .count()
    )

    if estados_restantes:
        raise RuntimeError(
            (
                "Quedaron "
                f"{estados_restantes} "
                "EstadoPasarelaPago "
                "sin Tenant."
            )
        )

    if eventos_restantes:
        raise RuntimeError(
            (
                "Quedaron "
                f"{eventos_restantes} "
                "EventoPagoWompi "
                "sin Tenant."
            )
        )

class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0026_estadopasarelapago_tenant_eventopagowompi_tenant_and_more'),
    ]

    operations = [
        migrations.RunPython(
            backfill_wompi_tenant,
            migrations.RunPython.noop,
        ),
    ]
