# Generated by Django 4.2.17 on 2026-09-10 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0027_backfill_wompi_tenant_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopasarelapago',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estado_pasarela_wompi', to='pedidos.tenant'),
        ),
        migrations.AlterField(
            model_name='eventopagowompi',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_pago_wompi', to='pedidos.tenant'),
        ),
    ]
