# Generated by Django 4.2.17 on 2026-09-11 00:06

from django.db import migrations

from django.db import migrations


def backfill_core_tenant_required(
    apps,
    schema_editor,
):
    Tenant = apps.get_model(
        "pedidos",
        "Tenant",
    )
    Sucursal = apps.get_model(
        "pedidos",
        "Sucursal",
    )
    ConfiguracionNegocio = apps.get_model(
        "pedidos",
        "ConfiguracionNegocio",
    )
    DiaEspecial = apps.get_model(
        "pedidos",
        "DiaEspecial",
    )
    Pedido = apps.get_model(
        "pedidos",
        "Pedido",
    )
    Categoria = apps.get_model(
        "pedidos",
        "Categoria",
    )
    Extra = apps.get_model(
        "pedidos",
        "Extra",
    )
    Producto = apps.get_model(
        "pedidos",
        "Producto",
    )
    PagoWompi = apps.get_model(
        "pedidos",
        "PagoWompi",
    )

    db = schema_editor.connection.alias

    tenant_ids = list(
        Tenant.objects
        .using(db)
        .values_list(
            "id",
            flat=True,
        )
    )

    sucursal_ids = list(
        Sucursal.objects
        .using(db)
        .values_list(
            "id",
            flat=True,
        )
    )

    # -------------------------------------------------
    # ConfiguracionNegocio -> Sucursal
    # -------------------------------------------------
    configuraciones = (
        ConfiguracionNegocio.objects
        .using(db)
        .filter(
            sucursal__isnull=True
        )
    )

    for config in configuraciones.iterator():

        if len(sucursal_ids) != 1:
            raise RuntimeError(
                (
                    "No fue posible determinar de forma "
                    "segura la Sucursal de "
                    f"ConfiguracionNegocio {config.pk}."
                )
            )

        ya_usada = (
            ConfiguracionNegocio.objects
            .using(db)
            .filter(
                sucursal_id=sucursal_ids[0]
            )
            .exclude(
                pk=config.pk
            )
            .exists()
        )

        if ya_usada:
            raise RuntimeError(
                (
                    "La única Sucursal disponible ya "
                    "tiene ConfiguracionNegocio."
                )
            )

        (
            ConfiguracionNegocio.objects
            .using(db)
            .filter(pk=config.pk)
            .update(
                sucursal_id=sucursal_ids[0]
            )
        )

    # -------------------------------------------------
    # DiaEspecial -> Sucursal
    # -------------------------------------------------
    for dia in (
        DiaEspecial.objects
        .using(db)
        .filter(
            sucursal__isnull=True
        )
        .iterator()
    ):
        if len(sucursal_ids) != 1:
            raise RuntimeError(
                (
                    "No fue posible determinar de forma "
                    "segura la Sucursal de "
                    f"DiaEspecial {dia.pk}."
                )
            )

        (
            DiaEspecial.objects
            .using(db)
            .filter(pk=dia.pk)
            .update(
                sucursal_id=sucursal_ids[0]
            )
        )

    # -------------------------------------------------
    # Pedido -> Sucursal
    # Se puede inferir por el Tenant del Cliente
    # únicamente si ese Tenant tiene una sola Sucursal.
    # -------------------------------------------------
    for pedido in (
        Pedido.objects
        .using(db)
        .filter(
            sucursal__isnull=True
        )
        .iterator()
    ):
        cliente_tenant_id = (
            Pedido.objects
            .using(db)
            .filter(pk=pedido.pk)
            .values_list(
                "cliente__tenant_id",
                flat=True,
            )
            .first()
        )

        posibles = list(
            Sucursal.objects
            .using(db)
            .filter(
                tenant_id=cliente_tenant_id
            )
            .values_list(
                "id",
                flat=True,
            )
        )

        if len(posibles) != 1:
            raise RuntimeError(
                (
                    "No fue posible determinar de forma "
                    "segura la Sucursal del "
                    f"Pedido {pedido.pk}."
                )
            )

        (
            Pedido.objects
            .using(db)
            .filter(pk=pedido.pk)
            .update(
                sucursal_id=posibles[0]
            )
        )

    # -------------------------------------------------
    # Categoria -> Tenant
    # -------------------------------------------------
    for categoria in (
        Categoria.objects
        .using(db)
        .filter(
            tenant__isnull=True
        )
        .iterator()
    ):
        encontrados = list(
            Pedido.objects
            .using(db)
            .filter(
                detalles__producto__categoria_id=(
                    categoria.pk
                ),
                sucursal__isnull=False,
            )
            .values_list(
                "sucursal__tenant_id",
                flat=True,
            )
            .distinct()
        )

        if len(encontrados) == 1:
            tenant_id = encontrados[0]

        elif (
            len(encontrados) == 0
            and len(tenant_ids) == 1
        ):
            tenant_id = tenant_ids[0]

        else:
            raise RuntimeError(
                (
                    "No fue posible determinar de forma "
                    "segura el Tenant de "
                    f"Categoria {categoria.pk}."
                )
            )

        (
            Categoria.objects
            .using(db)
            .filter(pk=categoria.pk)
            .update(
                tenant_id=tenant_id
            )
        )

    # -------------------------------------------------
    # Extra -> Tenant
    # Se deriva de los productos que lo utilizan.
    # -------------------------------------------------
    for extra in (
        Extra.objects
        .using(db)
        .filter(
            tenant__isnull=True
        )
        .iterator()
    ):
        encontrados = list(
            Producto.objects
            .using(db)
            .filter(
                extras=extra,
                categoria__tenant__isnull=False,
            )
            .values_list(
                "categoria__tenant_id",
                flat=True,
            )
            .distinct()
        )

        if len(encontrados) == 1:
            tenant_id = encontrados[0]

        elif (
            len(encontrados) == 0
            and len(tenant_ids) == 1
        ):
            tenant_id = tenant_ids[0]

        else:
            raise RuntimeError(
                (
                    "No fue posible determinar de forma "
                    "segura el Tenant de "
                    f"Extra {extra.pk}."
                )
            )

        (
            Extra.objects
            .using(db)
            .filter(pk=extra.pk)
            .update(
                tenant_id=tenant_id
            )
        )

    # -------------------------------------------------
    # PagoWompi -> Tenant
    # -------------------------------------------------
    for pago in (
        PagoWompi.objects
        .using(db)
        .filter(
            tenant__isnull=True
        )
        .iterator()
    ):
        datos = (
            PagoWompi.objects
            .using(db)
            .filter(pk=pago.pk)
            .values(
                "pedido__sucursal__tenant_id",
                "configuracion_negocio__sucursal__tenant_id",
            )
            .first()
        )

        candidatos = {
            tenant_id
            for tenant_id in [
                datos[
                    "pedido__sucursal__tenant_id"
                ],
                datos[
                    "configuracion_negocio__sucursal__tenant_id"
                ],
            ]
            if tenant_id
        }

        if len(candidatos) == 1:
            tenant_id = candidatos.pop()

        elif (
            len(candidatos) == 0
            and len(tenant_ids) == 1
        ):
            tenant_id = tenant_ids[0]

        else:
            raise RuntimeError(
                (
                    "No fue posible determinar de forma "
                    "segura el Tenant de "
                    f"PagoWompi {pago.pk}."
                )
            )

        (
            PagoWompi.objects
            .using(db)
            .filter(pk=pago.pk)
            .update(
                tenant_id=tenant_id
            )
        )

    # -------------------------------------------------
    # Verificación final
    # -------------------------------------------------
    comprobaciones = [
        (
            "ConfiguracionNegocio.sucursal",
            ConfiguracionNegocio.objects
            .using(db)
            .filter(
                sucursal__isnull=True
            )
            .count(),
        ),
        (
            "DiaEspecial.sucursal",
            DiaEspecial.objects
            .using(db)
            .filter(
                sucursal__isnull=True
            )
            .count(),
        ),
        (
            "Pedido.sucursal",
            Pedido.objects
            .using(db)
            .filter(
                sucursal__isnull=True
            )
            .count(),
        ),
        (
            "Categoria.tenant",
            Categoria.objects
            .using(db)
            .filter(
                tenant__isnull=True
            )
            .count(),
        ),
        (
            "Extra.tenant",
            Extra.objects
            .using(db)
            .filter(
                tenant__isnull=True
            )
            .count(),
        ),
        (
            "PagoWompi.tenant",
            PagoWompi.objects
            .using(db)
            .filter(
                tenant__isnull=True
            )
            .count(),
        ),
    ]

    errores = [
        f"{nombre}: {cantidad}"
        for nombre, cantidad in comprobaciones
        if cantidad
    ]

    if errores:
        raise RuntimeError(
            "Quedaron relaciones multi-tenant "
            "sin resolver: "
            + ", ".join(errores)
        )



class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0028_alter_estadopasarelapago_tenant_and_more'),
    ]

    operations = [
            migrations.RunPython(
                backfill_core_tenant_required,
                migrations.RunPython.noop,
            ),
        ]
