# Generated by Django 4.2.17 on 2026-09-11 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0029_backfill_core_tenant_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='pedidos.tenant'),
        ),
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='sucursal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configuracion', to='pedidos.sucursal'),
        ),
        migrations.AlterField(
            model_name='diaespecial',
            name='sucursal',
            field=models.ForeignKey(help_text='Sucursal a la que pertenece esta excepción de horario.', on_delete=django.db.models.deletion.PROTECT, related_name='dias_especiales', to='pedidos.sucursal'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extras_catalogo', to='pedidos.tenant'),
        ),
        migrations.AlterField(
            model_name='pagowompi',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_wompi', to='pedidos.tenant'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.sucursal'),
        ),
    ]
