# Generated by Django 4.2.17 on 2026-09-11 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0030_alter_categoria_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepartidorSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repartidores_asignados', to='pedidos.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foodback_delivery_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de repartidor',
                'verbose_name_plural': 'Asignaciones de repartidores',
                'indexes': [models.Index(fields=['usuario', 'activo'], name='delivery_user_active_idx'), models.Index(fields=['sucursal', 'activo'], name='delivery_branch_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='repartidorsucursal',
            constraint=models.UniqueConstraint(fields=('usuario', 'sucursal'), name='unique_repartidor_por_sucursal'),
        ),
    ]
