# Generated by Django 4.2.17 on 2026-09-11 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0031_repartidorsucursal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales_permitidas', to='pedidos.membership')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships_autorizados', to='pedidos.sucursal')),
            ],
            options={
                'verbose_name': 'Acceso administrativo a sucursal',
                'verbose_name_plural': 'Accesos administrativos a sucursales',
                'indexes': [models.Index(fields=['membership', 'activo'], name='member_branch_active_idx'), models.Index(fields=['sucursal', 'activo'], name='branch_member_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='membershipsucursal',
            constraint=models.UniqueConstraint(fields=('membership', 'sucursal'), name='unique_membership_por_sucursal'),
        ),
    ]
