# Generated by Django 4.2.17 on 2026-09-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0032_membershipsucursal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(db_index=True, max_length=80)),
                ('clave_hash', models.CharField(max_length=64, unique=True)),
                ('ventana_inicio', models.DateTimeField()),
                ('contador', models.PositiveIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['grupo', 'actualizado_en'], name='ratelimit_group_updated_idx')],
            },
        ),
    ]
