# Generated by Django 4.2.17 on 2026-09-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0033_ratelimitbucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='checkout_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
    ]
