# Generated by Django 4.2.17 on 2026-09-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0034_pedido_checkout_token'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['sucursal', 'actualizado_en'], name='pedido_suc_actual_idx'),
        ),
    ]
