# Generated by Django 4.2.17 on 2026-09-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0035_add_pedido_polling_index'),
    ]

    operations = [
    migrations.RunSQL(
        sql=r"""
            -- =============================================
            -- CATEGORIA
            -- =============================================
            ALTER TABLE pedidos_categoria
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_categoria;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_categoria
                USING (
                    tenant_id = NULLIF(
                        current_setting(
                            'foodback.tenant_id',
                            true
                        ),
                        ''
                    )::bigint
                )
                WITH CHECK (
                    tenant_id = NULLIF(
                        current_setting(
                            'foodback.tenant_id',
                            true
                        ),
                        ''
                    )::bigint
                );


            -- =============================================
            -- EXTRA
            -- =============================================
            ALTER TABLE pedidos_extra
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_extra;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_extra
                USING (
                    tenant_id = NULLIF(
                        current_setting(
                            'foodback.tenant_id',
                            true
                        ),
                        ''
                    )::bigint
                )
                WITH CHECK (
                    tenant_id = NULLIF(
                        current_setting(
                            'foodback.tenant_id',
                            true
                        ),
                        ''
                    )::bigint
                );


            -- =============================================
            -- CLIENTE
            -- =============================================
            ALTER TABLE pedidos_cliente
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_cliente;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_cliente
                USING (
                    tenant_id = NULLIF(
                        current_setting(
                            'foodback.tenant_id',
                            true
                        ),
                        ''
                    )::bigint
                )
                WITH CHECK (
                    tenant_id = NULLIF(
                        current_setting(
                            'foodback.tenant_id',
                            true
                        ),
                        ''
                    )::bigint
                );
        """,

        reverse_sql=r"""
            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_categoria;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_extra;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_cliente;

            ALTER TABLE pedidos_categoria
                DISABLE ROW LEVEL SECURITY;

            ALTER TABLE pedidos_extra
                DISABLE ROW LEVEL SECURITY;

            ALTER TABLE pedidos_cliente
                DISABLE ROW LEVEL SECURITY;
        """,
    ),
]
