# Generated by Django 4.2.17 on 2026-09-13 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0036_rls_categoria_extra_cliente'),
    ]

    operations = [
    migrations.RunSQL(
        sql=r"""
            -- =============================================
            -- PRODUCTO
            -- Tenant indirecto:
            -- Producto -> Categoria -> Tenant
            -- =============================================
            ALTER TABLE pedidos_producto
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_producto;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_producto
                USING (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_categoria categoria
                        WHERE
                            categoria.id =
                                pedidos_producto.categoria_id
                            AND categoria.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                )
                WITH CHECK (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_categoria categoria
                        WHERE
                            categoria.id =
                                pedidos_producto.categoria_id
                            AND categoria.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                );


            -- =============================================
            -- OPCION PRODUCTO
            -- Tenant indirecto:
            -- OpcionProducto -> Producto -> Categoria -> Tenant
            -- =============================================
            ALTER TABLE pedidos_opcionproducto
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_opcionproducto;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_opcionproducto
                USING (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_producto producto
                        INNER JOIN pedidos_categoria categoria
                            ON categoria.id =
                                producto.categoria_id
                        WHERE
                            producto.id =
                                pedidos_opcionproducto.producto_id
                            AND categoria.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                )
                WITH CHECK (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_producto producto
                        INNER JOIN pedidos_categoria categoria
                            ON categoria.id =
                                producto.categoria_id
                        WHERE
                            producto.id =
                                pedidos_opcionproducto.producto_id
                            AND categoria.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                );
        """,

        reverse_sql=r"""
            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_opcionproducto;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_producto;

            ALTER TABLE pedidos_opcionproducto
                DISABLE ROW LEVEL SECURITY;

            ALTER TABLE pedidos_producto
                DISABLE ROW LEVEL SECURITY;
        """,
    ),
]
