# Generated by Django 4.2.17 on 2026-09-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0037_rls_producto_opcionproducto'),
    ]

    operations = [
    migrations.RunSQL(
        sql=r"""
            -- =============================================
            -- PRODUCTO <-> EXTRA
            --
            -- Ambos extremos deben pertenecer al tenant
            -- PostgreSQL actualmente activo.
            -- =============================================
            ALTER TABLE pedidos_producto_extras
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_producto_extras;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_producto_extras
                USING (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_producto producto
                        INNER JOIN pedidos_categoria categoria
                            ON categoria.id = producto.categoria_id
                        WHERE
                            producto.id =
                                pedidos_producto_extras.producto_id
                            AND categoria.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                    AND
                    EXISTS (
                        SELECT 1
                        FROM pedidos_extra extra
                        WHERE
                            extra.id =
                                pedidos_producto_extras.extra_id
                            AND extra.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                )
                WITH CHECK (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_producto producto
                        INNER JOIN pedidos_categoria categoria
                            ON categoria.id = producto.categoria_id
                        WHERE
                            producto.id =
                                pedidos_producto_extras.producto_id
                            AND categoria.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                    AND
                    EXISTS (
                        SELECT 1
                        FROM pedidos_extra extra
                        WHERE
                            extra.id =
                                pedidos_producto_extras.extra_id
                            AND extra.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                );
        """,
        reverse_sql=r"""
            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_producto_extras;

            ALTER TABLE pedidos_producto_extras
                DISABLE ROW LEVEL SECURITY;
        """,
    ),
]
