# Generated by Django 4.2.17 on 2026-09-13 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0038_rls_producto_extras'),
    ]

    operations = [
    migrations.RunSQL(
        sql=r"""
            -- =============================================
            -- CONFIGURACION NEGOCIO
            -- Configuracion -> Sucursal -> Tenant
            -- =============================================
            ALTER TABLE pedidos_configuracionnegocio
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_configuracionnegocio;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_configuracionnegocio
                USING (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_sucursal sucursal
                        WHERE
                            sucursal.id =
                                pedidos_configuracionnegocio.sucursal_id
                            AND sucursal.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                )
                WITH CHECK (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_sucursal sucursal
                        WHERE
                            sucursal.id =
                                pedidos_configuracionnegocio.sucursal_id
                            AND sucursal.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                );


            -- =============================================
            -- DIA ESPECIAL
            -- DiaEspecial -> Sucursal -> Tenant
            -- =============================================
            ALTER TABLE pedidos_diaespecial
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_diaespecial;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_diaespecial
                USING (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_sucursal sucursal
                        WHERE
                            sucursal.id =
                                pedidos_diaespecial.sucursal_id
                            AND sucursal.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                )
                WITH CHECK (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_sucursal sucursal
                        WHERE
                            sucursal.id =
                                pedidos_diaespecial.sucursal_id
                            AND sucursal.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                );
        """,

        reverse_sql=r"""
            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_configuracionnegocio;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_diaespecial;

            ALTER TABLE pedidos_configuracionnegocio
                DISABLE ROW LEVEL SECURITY;

            ALTER TABLE pedidos_diaespecial
                DISABLE ROW LEVEL SECURITY;
        """,
    ),
]
