# Generated by Django 4.2.17 on 2026-09-13 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0039_rls_configuracion_diaespecial'),
    ]

    operations = [
    migrations.RunSQL(
        sql=r"""
            -- =============================================
            -- PEDIDO
            --
            -- Deben pertenecer al tenant activo:
            --
            -- 1. Pedido -> Sucursal -> Tenant
            -- 2. Pedido -> Cliente  -> Tenant
            --
            -- Esto impide pedidos híbridos entre tenants.
            -- =============================================

            ALTER TABLE pedidos_pedido
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_pedido;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_pedido
                USING (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_sucursal sucursal
                        WHERE
                            sucursal.id =
                                pedidos_pedido.sucursal_id
                            AND sucursal.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                    AND
                    EXISTS (
                        SELECT 1
                        FROM pedidos_cliente cliente
                        WHERE
                            cliente.id =
                                pedidos_pedido.cliente_id
                            AND cliente.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                )
                WITH CHECK (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_sucursal sucursal
                        WHERE
                            sucursal.id =
                                pedidos_pedido.sucursal_id
                            AND sucursal.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                    AND
                    EXISTS (
                        SELECT 1
                        FROM pedidos_cliente cliente
                        WHERE
                            cliente.id =
                                pedidos_pedido.cliente_id
                            AND cliente.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                );
        """,

        reverse_sql=r"""
            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_pedido;

            ALTER TABLE pedidos_pedido
                DISABLE ROW LEVEL SECURITY;
        """,
    ),
]
