# Generated by Django 4.2.17 on 2026-09-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0040_rls_pedido'),
    ]

    operations = [
    migrations.RunSQL(
        sql=r"""
            -- =============================================
            -- DETALLE PEDIDO
            --
            -- Deben ser coherentes con el tenant activo:
            -- Detalle -> Pedido
            -- Detalle -> Producto
            -- Detalle -> Opcion (si existe)
            -- =============================================

            ALTER TABLE pedidos_detallepedido
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_detallepedido;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_detallepedido
                USING (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_pedido pedido
                        WHERE
                            pedido.id =
                                pedidos_detallepedido.pedido_id
                    )
                    AND
                    EXISTS (
                        SELECT 1
                        FROM pedidos_producto producto
                        WHERE
                            producto.id =
                                pedidos_detallepedido.producto_id
                    )
                    AND
                    (
                        pedidos_detallepedido.opcion_id IS NULL
                        OR EXISTS (
                            SELECT 1
                            FROM pedidos_opcionproducto opcion
                            WHERE
                                opcion.id =
                                    pedidos_detallepedido.opcion_id
                                AND opcion.producto_id =
                                    pedidos_detallepedido.producto_id
                        )
                    )
                )
                WITH CHECK (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_pedido pedido
                        WHERE
                            pedido.id =
                                pedidos_detallepedido.pedido_id
                    )
                    AND
                    EXISTS (
                        SELECT 1
                        FROM pedidos_producto producto
                        WHERE
                            producto.id =
                                pedidos_detallepedido.producto_id
                    )
                    AND
                    (
                        pedidos_detallepedido.opcion_id IS NULL
                        OR EXISTS (
                            SELECT 1
                            FROM pedidos_opcionproducto opcion
                            WHERE
                                opcion.id =
                                    pedidos_detallepedido.opcion_id
                                AND opcion.producto_id =
                                    pedidos_detallepedido.producto_id
                        )
                    )
                );


            -- =============================================
            -- DETALLE PEDIDO <-> EXTRA
            --
            -- Detalle y Extra deben ser visibles dentro
            -- del mismo contexto tenant.
            -- =============================================

            ALTER TABLE pedidos_detallepedido_extras
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_detallepedido_extras;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_detallepedido_extras
                USING (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_detallepedido detalle
                        WHERE
                            detalle.id =
                                pedidos_detallepedido_extras.detallepedido_id
                    )
                    AND
                    EXISTS (
                        SELECT 1
                        FROM pedidos_extra extra
                        WHERE
                            extra.id =
                                pedidos_detallepedido_extras.extra_id
                    )
                )
                WITH CHECK (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_detallepedido detalle
                        WHERE
                            detalle.id =
                                pedidos_detallepedido_extras.detallepedido_id
                    )
                    AND
                    EXISTS (
                        SELECT 1
                        FROM pedidos_extra extra
                        WHERE
                            extra.id =
                                pedidos_detallepedido_extras.extra_id
                    )
                );
        """,

        reverse_sql=r"""
            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_detallepedido_extras;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_detallepedido;

            ALTER TABLE pedidos_detallepedido_extras
                DISABLE ROW LEVEL SECURITY;

            ALTER TABLE pedidos_detallepedido
                DISABLE ROW LEVEL SECURITY;
        """,
    ),
]