# Generated by Django 4.2.17 on 2026-09-13 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0041_rls_detallepedido_extras'),
    ]

    operations = [
    migrations.RunSQL(
        sql=r"""
            -- =============================================
            -- SUSCRIPCION TENANT
            -- =============================================
            ALTER TABLE pedidos_suscripciontenant
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_suscripciontenant;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_suscripciontenant
                USING (
                    tenant_id = NULLIF(
                        current_setting(
                            'foodback.tenant_id',
                            true
                        ),
                        ''
                    )::bigint
                )
                WITH CHECK (
                    tenant_id = NULLIF(
                        current_setting(
                            'foodback.tenant_id',
                            true
                        ),
                        ''
                    )::bigint
                );


            -- =============================================
            -- ESTADO PASARELA PAGO
            --
            -- tenant_id debe ser el tenant activo.
            --
            -- Si configuracion_negocio existe, también
            -- debe ser visible para ese mismo tenant.
            -- =============================================
            ALTER TABLE pedidos_estadopasarelapago
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_estadopasarelapago;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_estadopasarelapago
                USING (
                    tenant_id = NULLIF(
                        current_setting(
                            'foodback.tenant_id',
                            true
                        ),
                        ''
                    )::bigint

                    AND

                    (
                        configuracion_negocio_id IS NULL

                        OR EXISTS (
                            SELECT 1
                            FROM pedidos_configuracionnegocio configuracion
                            WHERE
                                configuracion.id =
                                    pedidos_estadopasarelapago.configuracion_negocio_id
                        )
                    )
                )
                WITH CHECK (
                    tenant_id = NULLIF(
                        current_setting(
                            'foodback.tenant_id',
                            true
                        ),
                        ''
                    )::bigint

                    AND

                    (
                        configuracion_negocio_id IS NULL

                        OR EXISTS (
                            SELECT 1
                            FROM pedidos_configuracionnegocio configuracion
                            WHERE
                                configuracion.id =
                                    pedidos_estadopasarelapago.configuracion_negocio_id
                        )
                    )
                );
        """,

        reverse_sql=r"""
            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_estadopasarelapago;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_suscripciontenant;

            ALTER TABLE pedidos_estadopasarelapago
                DISABLE ROW LEVEL SECURITY;

            ALTER TABLE pedidos_suscripciontenant
                DISABLE ROW LEVEL SECURITY;
        """,
    ),
]
