# Generated by Django 4.2.17 on 2026-09-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0042_rls_suscripcion_estado_pasarela'),
    ]

    operations = [
    migrations.RunSQL(
        sql=r"""
            -- =============================================
            -- PAGO WOMPI
            -- =============================================
            ALTER TABLE pedidos_pagowompi
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_pagowompi;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_pagowompi
                USING (
                    tenant_id = NULLIF(
                        current_setting(
                            'foodback.tenant_id',
                            true
                        ),
                        ''
                    )::bigint

                    AND (
                        pedido_id IS NULL
                        OR EXISTS (
                            SELECT 1
                            FROM pedidos_pedido pedido
                            WHERE
                                pedido.id =
                                    pedidos_pagowompi.pedido_id
                        )
                    )

                    AND (
                        configuracion_negocio_id IS NULL
                        OR EXISTS (
                            SELECT 1
                            FROM pedidos_configuracionnegocio configuracion
                            WHERE
                                configuracion.id =
                                    pedidos_pagowompi.configuracion_negocio_id
                        )
                    )
                )
                WITH CHECK (
                    tenant_id = NULLIF(
                        current_setting(
                            'foodback.tenant_id',
                            true
                        ),
                        ''
                    )::bigint

                    AND (
                        pedido_id IS NULL
                        OR EXISTS (
                            SELECT 1
                            FROM pedidos_pedido pedido
                            WHERE
                                pedido.id =
                                    pedidos_pagowompi.pedido_id
                        )
                    )

                    AND (
                        configuracion_negocio_id IS NULL
                        OR EXISTS (
                            SELECT 1
                            FROM pedidos_configuracionnegocio configuracion
                            WHERE
                                configuracion.id =
                                    pedidos_pagowompi.configuracion_negocio_id
                        )
                    )
                );


            -- =============================================
            -- EVENTO WOMPI
            -- =============================================
            ALTER TABLE pedidos_eventopagowompi
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_eventopagowompi;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_eventopagowompi
                USING (
                    tenant_id = NULLIF(
                        current_setting(
                            'foodback.tenant_id',
                            true
                        ),
                        ''
                    )::bigint

                    AND (
                        pago_id IS NULL
                        OR EXISTS (
                            SELECT 1
                            FROM pedidos_pagowompi pago
                            WHERE
                                pago.id =
                                    pedidos_eventopagowompi.pago_id
                        )
                    )

                    AND (
                        pedido_id IS NULL
                        OR EXISTS (
                            SELECT 1
                            FROM pedidos_pedido pedido
                            WHERE
                                pedido.id =
                                    pedidos_eventopagowompi.pedido_id
                        )
                    )

                    AND (
                        configuracion_negocio_id IS NULL
                        OR EXISTS (
                            SELECT 1
                            FROM pedidos_configuracionnegocio configuracion
                            WHERE
                                configuracion.id =
                                    pedidos_eventopagowompi.configuracion_negocio_id
                        )
                    )
                )
                WITH CHECK (
                    tenant_id = NULLIF(
                        current_setting(
                            'foodback.tenant_id',
                            true
                        ),
                        ''
                    )::bigint

                    AND (
                        pago_id IS NULL
                        OR EXISTS (
                            SELECT 1
                            FROM pedidos_pagowompi pago
                            WHERE
                                pago.id =
                                    pedidos_eventopagowompi.pago_id
                        )
                    )

                    AND (
                        pedido_id IS NULL
                        OR EXISTS (
                            SELECT 1
                            FROM pedidos_pedido pedido
                            WHERE
                                pedido.id =
                                    pedidos_eventopagowompi.pedido_id
                        )
                    )

                    AND (
                        configuracion_negocio_id IS NULL
                        OR EXISTS (
                            SELECT 1
                            FROM pedidos_configuracionnegocio configuracion
                            WHERE
                                configuracion.id =
                                    pedidos_eventopagowompi.configuracion_negocio_id
                        )
                    )
                );
        """,

        reverse_sql=r"""
            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_eventopagowompi;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_pagowompi;

            ALTER TABLE pedidos_eventopagowompi
                DISABLE ROW LEVEL SECURITY;

            ALTER TABLE pedidos_pagowompi
                DISABLE ROW LEVEL SECURITY;
        """,
    ),
]
