# Generated by Django 4.2.17 on 2026-09-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0043_rls_wompi_financial'),
    ]

    operations = [
    migrations.RunSQL(
        sql=r"""
            -- =============================================
            -- SUCURSAL
            -- =============================================

            ALTER TABLE pedidos_sucursal
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_sucursal;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_sucursal
                USING (
                    tenant_id = NULLIF(
                        current_setting(
                            'foodback.tenant_id',
                            true
                        ),
                        ''
                    )::bigint
                )
                WITH CHECK (
                    tenant_id = NULLIF(
                        current_setting(
                            'foodback.tenant_id',
                            true
                        ),
                        ''
                    )::bigint
                );


            -- =============================================
            -- MEMBERSHIP <-> SUCURSAL
            --
            -- Ambos extremos deben pertenecer al
            -- Tenant PostgreSQL activo.
            -- =============================================

            ALTER TABLE pedidos_membershipsucursal
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_membershipsucursal;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_membershipsucursal
                USING (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_membership membership
                        WHERE
                            membership.id =
                                pedidos_membershipsucursal.membership_id
                            AND membership.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                    AND
                    EXISTS (
                        SELECT 1
                        FROM pedidos_sucursal sucursal
                        WHERE
                            sucursal.id =
                                pedidos_membershipsucursal.sucursal_id
                            AND sucursal.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                )
                WITH CHECK (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_membership membership
                        WHERE
                            membership.id =
                                pedidos_membershipsucursal.membership_id
                            AND membership.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                    AND
                    EXISTS (
                        SELECT 1
                        FROM pedidos_sucursal sucursal
                        WHERE
                            sucursal.id =
                                pedidos_membershipsucursal.sucursal_id
                            AND sucursal.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                );


            -- =============================================
            -- REPARTIDOR <-> SUCURSAL
            --
            -- El usuario auth es global.
            -- El aislamiento Tenant viene dado por
            -- la Sucursal asignada.
            -- =============================================

            ALTER TABLE pedidos_repartidorsucursal
                ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_repartidorsucursal;

            CREATE POLICY foodback_tenant_isolation
                ON pedidos_repartidorsucursal
                USING (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_sucursal sucursal
                        WHERE
                            sucursal.id =
                                pedidos_repartidorsucursal.sucursal_id
                            AND sucursal.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                )
                WITH CHECK (
                    EXISTS (
                        SELECT 1
                        FROM pedidos_sucursal sucursal
                        WHERE
                            sucursal.id =
                                pedidos_repartidorsucursal.sucursal_id
                            AND sucursal.tenant_id =
                                NULLIF(
                                    current_setting(
                                        'foodback.tenant_id',
                                        true
                                    ),
                                    ''
                                )::bigint
                    )
                );
        """,

        reverse_sql=r"""
            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_repartidorsucursal;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_membershipsucursal;

            DROP POLICY IF EXISTS
                foodback_tenant_isolation
                ON pedidos_sucursal;

            ALTER TABLE pedidos_repartidorsucursal
                DISABLE ROW LEVEL SECURITY;

            ALTER TABLE pedidos_membershipsucursal
                DISABLE ROW LEVEL SECURITY;

            ALTER TABLE pedidos_sucursal
                DISABLE ROW LEVEL SECURITY;
        """,
    ),
]
