# Generated by Django 4.2.17 on 2026-09-15 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0044_rls_branch_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_verified', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foodback_staff_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identidad de personal',
                'verbose_name_plural': 'Identidades de personal',
            },
        ),
        migrations.AddConstraint(
            model_name='staffidentity',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('email')), name='staff_identity_email_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='staffidentity',
            constraint=models.CheckConstraint(check=models.Q(('email__regex', '^\\s*$'), _negated=True), name='staff_identity_email_not_empty'),
        ),
    ]
