# Generated by Django 4.2.17 on 2026-09-15 04:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0045_staffidentity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('codigo_hash', models.CharField(max_length=128)),
                ('expira_en', models.DateTimeField()),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_challenges', to='pedidos.staffidentity')),
            ],
            options={
                'verbose_name': 'Desafío de recuperación de contraseña',
                'verbose_name_plural': 'Desafíos de recuperación de contraseña',
                'indexes': [models.Index(fields=['identity', 'creado_en'], name='pwdreset_identity_created_idx')],
            },
        ),
    ]
