# Generated by Django 4.2.17 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0046_passwordresetchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetchallenge',
            name='completado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='passwordresetchallenge',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(completado_en__isnull=True)
                    | models.Q(usado_en__isnull=False)
                ),
                name='pwdreset_complete_requires_used',
            ),
        ),
    ]
