# Generated for FoodBack Phase 7 audit foundation.

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
        (
            "pedidos",
            "0047_passwordresetchallenge_completado_en",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "evento",
                    models.CharField(
                        max_length=120,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            (
                                "AUTENTICACION",
                                "Autenticación",
                            ),
                            (
                                "AUTORIZACION",
                                "Autorización",
                            ),
                            (
                                "SEGURIDAD",
                                "Seguridad",
                            ),
                            (
                                "CUENTA",
                                "Cuenta",
                            ),
                            (
                                "ADMINISTRACION",
                                "Administración",
                            ),
                            (
                                "PAGOS",
                                "Pagos",
                            ),
                            (
                                "SISTEMA",
                                "Sistema",
                            ),
                            (
                                "SOPORTE",
                                "Soporte",
                            ),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            (
                                "INFO",
                                "Informativa",
                            ),
                            (
                                "BAJA",
                                "Baja",
                            ),
                            (
                                "MEDIA",
                                "Media",
                            ),
                            (
                                "ALTA",
                                "Alta",
                            ),
                            (
                                "CRITICA",
                                "Crítica",
                            ),
                        ],
                        default="INFO",
                        max_length=16,
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            (
                                "INFORMATIVO",
                                "Informativo",
                            ),
                            (
                                "EXITO",
                                "Éxito",
                            ),
                            (
                                "FALLO",
                                "Fallo",
                            ),
                            (
                                "BLOQUEADO",
                                "Bloqueado",
                            ),
                            (
                                "DENEGADO",
                                "Denegado",
                            ),
                            (
                                "ERROR",
                                "Error",
                            ),
                        ],
                        default="INFORMATIVO",
                        max_length=16,
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        choices=[
                            (
                                "WEB",
                                "Web",
                            ),
                            (
                                "SISTEMA",
                                "Sistema",
                            ),
                            (
                                "WEBHOOK",
                                "Webhook",
                            ),
                            (
                                "TAREA",
                                "Tarea",
                            ),
                        ],
                        default="WEB",
                        max_length=16,
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
                (
                    "actor_tipo",
                    models.CharField(
                        choices=[
                            (
                                "ANONIMO",
                                "Anónimo",
                            ),
                            (
                                "USUARIO",
                                "Usuario",
                            ),
                            (
                                "SISTEMA",
                                "Sistema",
                            ),
                        ],
                        default="ANONIMO",
                        max_length=16,
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(
                        blank=True,
                        max_length=150,
                    ),
                ),
                (
                    "actor_role",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "tenant_public_id",
                    models.UUIDField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "tenant_nombre",
                    models.CharField(
                        blank=True,
                        max_length=150,
                    ),
                ),
                (
                    "sucursal_public_id",
                    models.UUIDField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "sucursal_nombre",
                    models.CharField(
                        blank=True,
                        max_length=150,
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "metodo_http",
                    models.CharField(
                        blank=True,
                        max_length=10,
                    ),
                ),
                (
                    "ruta",
                    models.CharField(
                        blank=True,
                        max_length=500,
                    ),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        max_length=300,
                    ),
                ),
                (
                    "objeto_tipo",
                    models.CharField(
                        blank=True,
                        max_length=80,
                    ),
                ),
                (
                    "objeto_id",
                    models.CharField(
                        blank=True,
                        max_length=120,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        max_length=64,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                    ),
                ),
                (
                    "actor_usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=(
                            django.db.models.deletion.SET_NULL
                        ),
                        related_name=(
                            "foodback_audit_events"
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de auditoría",
                "verbose_name_plural": (
                    "Eventos de auditoría"
                ),
                "ordering": [
                    "-creado_en",
                ],
                "indexes": [
                    models.Index(
                        fields=[
                            "categoria",
                            "-creado_en",
                        ],
                        name="audit_category_created_idx",
                    ),
                    models.Index(
                        fields=[
                            "severidad",
                            "-creado_en",
                        ],
                        name="audit_severity_created_idx",
                    ),
                    models.Index(
                        fields=[
                            "tenant_public_id",
                            "-creado_en",
                        ],
                        name="audit_tenant_created_idx",
                    ),
                    models.Index(
                        fields=[
                            "sucursal_public_id",
                            "-creado_en",
                        ],
                        name="audit_branch_created_idx",
                    ),
                    models.Index(
                        fields=[
                            "ip",
                            "-creado_en",
                        ],
                        name="audit_ip_created_idx",
                    ),
                    models.Index(
                        fields=[
                            "evento",
                            "-creado_en",
                        ],
                        name="audit_event_created_idx",
                    ),
                    models.Index(
                        fields=[
                            "fingerprint",
                            "-creado_en",
                        ],
                        name="audit_fprint_created_idx",
                    ),
                ],
            },
        ),
    ]
