import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
        (
            "pedidos",
            "0050_securityincident_state_constraints",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "source_request_id",
                    models.UUIDField(
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "submission_request_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            (
                                "ERROR_HTTP",
                                "Pantalla de error HTTP",
                            ),
                        ],
                        default="ERROR_HTTP",
                        max_length=24,
                    ),
                ),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            (
                                "ABIERTO",
                                "Abierto",
                            ),
                            (
                                "EN_REVISION",
                                "En revisión",
                            ),
                            (
                                "RESUELTO",
                                "Resuelto",
                            ),
                        ],
                        db_index=True,
                        default="ABIERTO",
                        max_length=20,
                    ),
                ),
                (
                    "mensaje",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(
                        blank=True,
                        max_length=150,
                    ),
                ),
                (
                    "actor_role",
                    models.CharField(
                        blank=True,
                        max_length=40,
                    ),
                ),
                (
                    "tenant_public_id",
                    models.UUIDField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "tenant_nombre",
                    models.CharField(
                        blank=True,
                        max_length=150,
                    ),
                ),
                (
                    "sucursal_public_id",
                    models.UUIDField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "sucursal_nombre",
                    models.CharField(
                        blank=True,
                        max_length=150,
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "actor_usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=(
                            django.db.models.deletion.SET_NULL
                        ),
                        related_name=(
                            "foodback_support_reports"
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": (
                    "Reporte de soporte"
                ),
                "verbose_name_plural": (
                    "Reportes de soporte"
                ),
                "ordering": [
                    "-creado_en",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="supportreport",
            constraint=models.CheckConstraint(
                check=models.Q(
                    http_status__in=[
                        400,
                        403,
                        404,
                        500,
                    ],
                ),
                name=(
                    "support_http_status_allowed"
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="supportreport",
            index=models.Index(
                fields=[
                    "estado",
                    "-creado_en",
                ],
                name=(
                    "support_state_created_idx"
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="supportreport",
            index=models.Index(
                fields=[
                    "tenant_public_id",
                    "-creado_en",
                ],
                name=(
                    "support_tenant_created_idx"
                ),
            ),
        ),
    ]
